### ISSUE TITLE
Swift Version ?

### ISSUE THREAD

**Issue by TheAbstractDev** [mrustaa/ContainerView#1]
Hi!

Thanks for your work but do you plan to create a Swift version ??

**Comment by mrustaa** [comment]
Thank you for your positive review! 
I will try to make a version of "Swift" in the near future.

**Comment by mrustaa** [comment]
Released a version on [swift](https://github.com/mrustaa/ContainerController), with a new architecture and parameters. current version app-example (objective c) is no longer supported.
